export const columns = [
  { field: "id", header: "#" },
  { field: "order", header: "Order" },
  { field: "user", header: "User" },
  { field: "delivery_boy", header: "Delivery Boy" },
  { field: "price", header: "Price" },
  { field: "status", header: "Status" },
  { field: "type", header: "Type" },
  { field: "order_type", header: "Order Type" },
  { field: "completed", header: "Completed" },
  { field: "created", header: "Created" },
];

export const data = [
  {
    id: 1001,
    order: 3674,
    user: "Lucky Shrivas",
    delivery_boy: "Demo Rajesh",
    price: "INR 639.17 (CASH)",
    status: "Delivered",
    type: "Delivery",
    order_type: "Store",
    completed: "19 Apr 2024 03:47 PM",
    created: "19 Apr 2024 03:41 PM",
  },
  {
    id: 1002,
    order: 3673,
    user: "Lucky Shrivas",
    delivery_boy: "Demo Rajesh",
    price: "INR 639.17 (CASH)",
    status: "Delivered",
    type: "Delivery",
    order_type: "Store",
    completed: "19 Apr 2024 03:47 PM",
    created: "19 Apr 2024 03:41 PM",
  },
  {
    id: 10013,
    order: 3672,
    user: "Lucky Shrivas",
    delivery_boy: "Demo Rajesh",
    price: "INR 639.17 (CASH)",
    status: "Delivered",
    type: "Delivery",
    order_type: "Store",
    completed: "19 Apr 2024 03:47 PM",
    created: "19 Apr 2024 03:41 PM",
  },
];
